<a href="https://colab.research.google.com/github/Sambaran04/Tensorflow/blob/main/Basics_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This is the notebook for basics of Tensorflow

In [27]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [28]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [29]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [30]:
# crate a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [31]:
# Check the dimension of our vector
vector.ndim

1

In [32]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [33]:
another_matrix = tf.constant([[10.,7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter

In [34]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

## Getting Information From Tensors##
size
shape
dimmension
access

In [35]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])

In [36]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [37]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape or tensor: ", rank_4_tensor.shape)
print("Element along the 0 exis: ", rank_4_tensor.shape[0])
print("Element along the last exis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape or tensor:  (2, 3, 4, 5)
Element along the 0 exis:  2
Element along the last exis:  5
Total number of elements in our tensor:  120


In [38]:
# Add in extra dimension
rank_2_tensor = tf.zeros(shape=[2, 2])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [39]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [40]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [41]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]]], dtype=float32)>

### Manipulating Tensors (Tensor Operations)
**Basic Operations**

`+`, `-`, `*`, `/`

In [42]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [43]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [44]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [45]:
tensor /10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [46]:
# We can use the tensorflow build-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### ***Matrix Multiplication***

In Machine Learning, Matrix Multiplication is one of the most common tensor operation

In [47]:
# Matrix Multiplication with tensorflow
matrix_1 = tf.constant([[5, 2],
                       [10, 7],
                        [10, 9]])
matrix_2 = tf.constant([[10, 7],
                        [5, 2],
                        [1, 6]])
tf.linalg.matmul(matrix_1, matrix_2, transpose_a = True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 115],
       [ 64,  82]], dtype=int32)>

In [48]:
# Matrix Multiplication with python operator '@'
# matrix_1 @ matrix_2

InvalidArgumentError: ignored